stages:          # List of stages for jobs, and their order of execution
  - build

docker-build:
  # Use the official docker image.
  image: docker/compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker version
    - docker-compose version
  script:
    - docker login cloudplus.azurecr.io
    - docker-compose build
    - docker-compose push
  
