version: "3"
services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 5432
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - HOST=${HOST}
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    # depends_on:
    #   - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: [ "npm", "start" ]
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
