version: "3"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000

  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
    ports:
      - 5438:5432
    volumes:
      - '/etc/postgresql' #'/var/log/postgresql', '/var/lib/postgresql']

  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command : ["npm","start"]
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000

# volumes:
#   postgres:
#     driver: local
  