install-python:
pip install -r requirements.txt

install-node:
npm install

test:
	PYTHONPATH=./src pytest

format-python and format-js:
black *.py
prettier *.js

lint:
pylint —disable = R,C app.py

all: install-python install-node format-python format-is lint
